name: 'kirick13/setup-ansible-core'
description: 'Installs Ansible Core inside GitHub Actions.'

inputs:
  version:
    description: 'Version of Ansible Core to install.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Cache Pip
      uses: actions/cache@v4
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ runner.os }}-${{ inputs.version }}

    - name: Install Ansible Core
      run: |
        pip install ansible-core==${{ inputs.version }}
